spring:
  application:
    name: eureka-feign-client
  mvc:
    view:
      suffix: .html
      prefix: /templates/
server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


